Feat/add nlb
cloudposse/terraform-aws-elastic-beanstalk-environment pull request #182
Opened 2021-06-14 16:59 UTC by florian0410

## what
* Add NLB support in the module
* Set default protocol to TCP in case that loadbalancer_type == "network"
* S3 logs and Security Groups are not valid for Network ELB. 

## why
* Module does not support yet NLB integration

## references
* Closes issue #66 
* Closes PR #176
* Closes PR #105   
* Closes PR #101

2021-06-14 17:42 UTC, florian0410 commented
I think we need another example case for nlb.

The StickinessEnabled additional setting of alb is not compatible with NLB currently.

Does the CI handle a multi example case ? I don't think I can set it up alone here.

2021-06-14 18:31 UTC, korenyoni commented
> I think we need another example case for nlb.
> 
> The StickinessEnabled additional setting of alb is not compatible with NLB currently.
> 
> Does the CI handle a multi example case ? I don't think I can set it up alone here.

@florian0410 Yes.

Let's say you are going to add a new example directory `examples/nlb`, you should also add a `examples_nlb_test.go` file to `test/src/` and also invoke it right below https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/blob/master/test/src/Makefile#L17

> I also need help for the bridgecrew error.

Without digging too deep, this seems like a BridgeCrew bug because `s3_bucket_versioning_enabled` is set to true by default. I would add `#bridgecrew:skip=BC_AWS_S3_16` to the `aws_s3_bucket.elb_logs` resource block and reference this PR in the Bridgecrew policy skip description. Better yet, I would open up an issue in https://github.com/bridgecrewio/checkov and reference the issue in the Bridgecrew policy skip description.

2021-06-14 19:59 UTC, jamengual commented
/test all

2021-06-15 16:37 UTC, florian0410 commented
I just added a new example following your advices. I'm not fully used to go yet so I may have done errors but I should have added the essential.

For the bridgecrew I added the exception, but I didn't open an issue for now since I'm not used to the tool. I'll let you handle this one if you don't mind. After a quick search since I use a count condition I think it may be linked to the following issue: https://github.com/bridgecrewio/checkov/issues/1078

But not sure yet so I'll let you check this.

@korenyoni

2021-06-15 16:53 UTC, korenyoni commented
/test all

2021-06-15 17:28 UTC, korenyoni commented
@florian0410 see: https://github.com/cloudposse/actions/runs/2831747735?check_suite_focus=true#step:9:2094

2021-06-15 17:52 UTC, florian0410 commented
Fixed @korenyoni I rebased also to the new version 0.41.0 by the way.

2021-06-15 17:53 UTC, korenyoni commented
/test all

2021-06-15 18:14 UTC, korenyoni requested changes
Still failing https://github.com/cloudposse/actions/runs/2832178965?check_suite_focus=true#step:9:2008

2021-06-15 18:14 UTC, korenyoni commented on examples/nlb/fixtures.us-east-2.tfvars
> +
```suggestion
updating_max_batch = 1

healthcheck_url = "/"

```

2021-06-15 18:14 UTC, korenyoni commented on examples/nlb/main.tf
> +  allowed_security_groups = [module.vpc.vpc_default_security_group_id]
```suggestion
  security_group_rules = [
    {
      type                     = "egress"
      from_port                = 0
      to_port                  = 65535
      protocol                 = "-1"
      cidr_blocks              = ["0.0.0.0/0"]
      source_security_group_id = null
      description              = "Allow all outbound traffic"
    },
    {
      type                     = "ingress"
      from_port                = 0
      to_port                  = 65535
      protocol                 = "-1"
      cidr_blocks              = []
      source_security_group_id = module.vpc.vpc_default_security_group_id
      description              = "Allow all inbound traffic from trusted Security Groups"
    },
  ]
```

2021-06-15 18:14 UTC, korenyoni commented on examples/nlb/fixtures.us-east-2.tfvars
> +
```suggestion
```

2021-06-15 18:39 UTC, florian0410 commented on examples/nlb/fixtures.us-east-2.tfvars
> +
healthcheck_url  is not compatible with NLB so I would remove it instead.

2021-06-15 18:44 UTC, korenyoni commented
/test all

2021-06-15 18:50 UTC, korenyoni commented
/test all

2021-06-18 18:17 UTC, florian0410 commented
Any need or remarks for the review ?
@korenyoni

2021-06-24 14:50 UTC, florian0410 commented
Added one of your suggestion @korenyoni.

Checks should succeed, normally. Do you know if we could merge this one soon ?

2021-06-24 14:53 UTC, Gowiem commented
/test all

2021-06-24 14:54 UTC, Gowiem commented
@florian0410 you're one of the primary contributors to this module... would you be interested in becoming a maintainer for it? I believe @osterman is still looking around for someone.

2021-06-24 15:17 UTC, florian0410 commented
> @florian0410 you're one of the primary contributors to this module... would you be interested in becoming a maintainer for it? I believe @osterman is still looking around for someone.

I think I can give it a try yes. You can ping me on slack to talk about it

2021-06-24 15:55 UTC, osterman commented
@florian0410 looks like we have too many "florians" on SweetOps, so I cannot find you. Can you DM me on slack?

2021-06-28 09:49 UTC, florian0410 commented
Hello,

Can we run again the tests ? It sounds like previous checks encountered a random NAT issue and I added some enhancement to this PR since last time.
I cannot see the bridgecrew  error also.


Regards

2021-07-18 11:42 UTC, florian0410 commented
/test all

2021-07-20 14:59 UTC, Gowiem approved these changes
Looks solid to me @florian0410 💯 

If you want a more keen set of eyes on this work before merging then you can wait for a final review from @korenyoni as it seems he's been on top of this one so far.

2021-07-26 08:05 UTC, merged

2021-07-26 08:12 UTC, florian0410 commented
Just released version 0.42.0.

Thank you all for your help and reviews !