Fixed sort function crashing when create_security_group=false
cloudposse/terraform-aws-elastic-beanstalk-environment pull request #229
Opened 2023-03-14 14:04 UTC by dawidrogowicz

## what
* Default to empty string if `aws_security_group.id` is null. Empty string will then get filtered out by compact().

## why
* Null value caused sort() function to crash, making it impossible to set `create_security_group` to `false`

## references
* https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/issues/216

2023-03-15 23:09 UTC, joe-niland commented
Hi @dawidrogowicz 

Could you please run the following and commit the result?

```
make init
make github/init
```

Thanks!

2023-03-15 23:10 UTC, joe-niland commented
/test all

2023-03-17 08:37 UTC, dawidrogowicz commented
> Hi @dawidrogowicz
> 
> Could you please run the following and commit the result?
> 
> ```
> make init
> make github/init
> ```
> 
> Thanks!

@joe-niland done :heavy_check_mark: Let me know if anything more is needed

2023-03-17 09:35 UTC, joe-niland commented
/test all

2023-03-17 10:04 UTC, joe-niland submitted a review, later dismissed

2023-06-07 10:05 UTC, SamCrudge commented
Can we have this PR looked at as its a blocker for quite a few projects?

2023-06-07 12:23 UTC, jamengual commented
@dawidrogowicz could you please fix the conflicts ? thanks

2023-06-07 13:20 UTC, dawidrogowicz commented
@jamengual done, let me know if you need any more updates from me

2023-06-07 13:36 UTC, jamengual commented
/terratest

2023-06-07 15:45 UTC, jamengual commented
please run `make precommit/terraform`

2023-06-07 16:25 UTC, jamengual commented
to fix the terratest failures please update the `example/complete/main.tf` and update the modules to the newest versions, recent updates to aws provider v5 and s3 are needed.

Thanks.

2023-06-14 05:14 UTC, dawidrogowicz commented
@jamengual I updated modules and rebuild docs with precommit/terraform. Example stayed the same as there should be no changes in how module is used

2023-06-19 19:54 UTC, jamengual commented
you will need to do 
```
make init
make readme
``` since still complains about the readme and make sure to push all the files changes
the make command will automatically change a lot of files

2023-06-28 14:58 UTC, goruha requested changes

2023-06-28 14:58 UTC, goruha commented on main.tf
> +    value     = join(",", compact(sort(concat([module.aws_security_group.id == null ? "" : module.aws_security_group.id], var.associated_security_group_ids))))
```suggestion
    value     = join(",", sort(compact(concat([module.aws_security_group.id], var.associated_security_group_ids))))
```
@dawidrogowicz  Would this fix the problem?

2023-07-13 01:30 UTC, eanselmi commented
Hi everyone! Any workaround until this solution is merged? Thanks!

2023-07-26 13:43 UTC, dawidrogowicz commented
closing since fix was merged here https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/244

2023-07-26 13:43 UTC, closed without merging