Groundwork new workflows
cloudposse/terraform-aws-elastic-beanstalk-environment pull request #232
Opened 2023-03-27 16:53 UTC by max-lobur

Fix lint/format before workflows rollout

2023-03-27 16:56 UTC, max-lobur commented
/test all

2023-03-27 20:32 UTC, goruha approved these changes

2023-03-27 20:32 UTC, goruha requested changes

2023-03-27 20:32 UTC, goruha commented on variables.tf
> -variable "ssh_source_restriction" {
Why we removed this

2023-03-28 09:52 UTC, max-lobur commented on variables.tf
> -variable "ssh_source_restriction" {
unused variable

2023-03-28 10:50 UTC, goruha approved these changes

2023-03-28 10:50 UTC, merged